services:
  client:
    image: pex9990/kiruna-explorer:client
    ports:
      - "5173:5173"
    networks:
      - kirunaexplorer-network
  server:
    image: pex9990/kiruna-explorer:server
    ports:
      - "3001:3001"
    networks:
      - kirunaexplorer-network
networks:
  kirunaexplorer-network:
    driver: bridge
