services:
  client:
    image: kirunaexplorer-client
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    networks:
      - kirunaexplorer-network
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    networks:
      - kirunaexplorer-network
networks:
  kirunaexplorer-network:
    driver: bridge